### ISSUE TITLE
Fresh tofino install white screen of death

### ISSUE THREAD

**Issue by jonXmack** [lambdacreatives/tofino#131]
Just setup a fresh tofino install and was getting WSOD until I updated the reading settings to display a static page.

**Comment by danimalweb** [comment]
Anything in the error logs?

**Comment by danimalweb** [comment]
Looks like expected behaviour, although maybe confusing.

Out of the box, Tofino does not have templates for a default "Posts shown" style setup. In this scenario, the white screen you are seeing is index.php which is empty. My installer automatically creates a new page and updates the reading settings to this static page so I've never seen this issue.

I recently updated the [templates readme](https://github.com/lambdacreatives/tofino/blob/master/templates/README.md).

**Comment by danimalweb** [comment]
An error message will be displayed if the page display settings set to Latest posts and the home.php file does not exist.
