### ISSUE TITLE
Can't install as a zip file

### ISSUE THREAD

**Issue by mrchimp** [lambdacreatives/tofino#41]
If you download the zip file and install it into wp via the admin area you end up with a white screen of death. I'm assuming this is because the npm/bower/composer/gulp tasks need running. Is there some kind of WP hook for this?

**Comment by danimalweb** [comment]
It's white screening because its trying to load a composer file autoload.php

I'll add a warning at the top of the admin page on theme activation if autoload.php is not found and how to build the theme - link to Readme.

For tagged release we can upload our own zip files.

I'll also provide a link to an up to date pre-built version hosted on my dev server.

That should cover all bases.
